import numpy as np
import ccxt

#exchanges = ["Mercado", "Binance", "Bitfinex", "Bittrex", "Cex", "Cryptopia", "Exmo", "Gatecoin", "Hitbtc",
#"Huobipro", "Kraken", "Kucoin", "Livecoin", "Okex", "Poloniex", "Qryptos", "Quadrigacx", "Southxchange", "Yobit"]

exchanges = ["Cex", "Qryptos", "mercado", "foxbit", "negociecoins", "braziliex", "Poloniex", "bleutrade"]

allcoin = ccxt.allcoin()

clients = [getattr(ccxt, e.lower())() for e in exchanges]

symbols = ["ETH/BTC", "ETC/BTC", "LTC/BTC","ADA/BTC", "BCH/BTC", "BTG/BTC", "BTS/BTC", "CLAIM/BTC", "DASH/BTC", "DOGE/BTC", "EDO/BTC", "EOS/BTC",
           "ETC/BTC","ETH/BTC", "FCT/BTC", "ICX/BTC", "IOTA/BTC", "LSK/BTC", "LTC/BTC", "MAID/BTC", "NEO/BTC",
           "OMG/BTC", "QTUM/BTC", "STR/BTC", "TRX/BTC","VEN/BTC", "XEM/BTC", "XLM/BTC", "XMR/BTC", "XRP/BTC", "ZEC/BTC",
		   "BTC/EUR",
"BTC/EUR",
"BTC/GBP",
"BTC/USD",
"ETH/EUR",
"ETH/JPY",
"ETH/GBP",
"ETH/USD",
"ETH/BTC",
"EOS/EUR",
"EOS/JPY",
"EOS/GBP",
"EOS/USD",
"EOS/BTC",
"EOS/ETH",
"LTC/USD",
"LTC/BTC",
"XRP/USD",
"XRP/BTC",
"IOTA/EUR",
"IOTA/JPY",
"IOTA/GBP",
"IOTA/USD",
"IOTA/BTC",
"IOTA/ETH",
"NEO/EUR",
"NEO/JPY",
"NEO/GBP",
"NEO/USD",
"NEO/BTC",
"NEO/ETH",
"ETC/USD",
"ETC/BTC",
"OMG/USD",
"OMG/BTC",
"OMG/ETH",
"XMR/USD",
"XMR/BTC",
"DASH/USD",
"DASH/BTC",
"TRX/EUR",
"TRX/JPY",
"TRX/GBP",
"TRX/USD",
"TRX/BTC",
"TRX/ETH",
"ZEC/USD",
"ZEC/BTC",
"BTG/USD",
"BTG/BTC",
"SAN/USD",
"SAN/BTC",
"SAN/ETH",
"ZRX/USD",
"ZRX/BTC",
"ZRX/ETH",
"EDO/USD",
"EDO/BTC",
"EDO/ETH",
"ETP/USD",
"ETP/BTC",
"ETP/ETH",
"QTUM/USD",
"QTUM/BTC",
"QTUM/ETH",
"BAT/USD",
"BAT/BTC",
"BAT/ETH",
"SNT/USD",
"SNT/BTC",
"SNT/ETH",
"AID/USD",
"AID/BTC",
"AID/ETH",
"REP/USD",
"REP/BTC",
"REP/ETH",
"QASH/USD",
"QASH/BTC",
"QASH/ETH",
"YYW/USD",
"YYW/BTC",
"YYW/ETH",
"DATA/USD",
"DATA/BTC",
"DATA/ETH",
"GNT/USD",
"GNT/BTC",
"GNT/ETH",
"TNB/USD",
"TNB/BTC",
"TNB/ETH",
"FUN/USD",
"FUN/BTC",
"FUN/ETH",
"SPK/USD",
"SPK/BTC",
"SPK/ETH",
"RLC/USD",
"RLC/BTC",
"RLC/ETH",
"ELF/USD",
"ELF/BTC",
"ELF/ETH",
"AVT/USD",
"AVT/BTC",
"AVT/ETH",
"MNA/USD",
"MNA/BTC",
"MNA/ETH",
"RCN/USD",
"RCN/BTC",
"RCN/ETH",
"SNG/USD",
"SNG/BTC",
"SNG/ETH",
"RRT/USD",
"RRT/BTC",
"IOS/USD",
"IOS/BTC",
"IOS/ETH",
"AIO/USD",
"AIO/BTC",
"AIO/ETH",
"REQ/USD",
"REQ/BTC",
"REQ/ETH",
"RDN/USD",
"RDN/BTC",
"RDN/ETH",
"LRC/USD",
"LRC/BTC",
"LRC/ETH",
"WAX/USD",
"WAX/BTC",
"WAX/ETH",
"DAI/USD",
"DAI/BTC",
"DAI/ETH",
"AGI/USD",
"AGI/BTC",
"AGI/ETH",
"BFT/USD",
"BFT/BTC",
"BFT/ETH",
"MTN/USD",
"MTN/BTC",
"MTN/ETH",
"ODE/USD",
"ODE/BTC",
"ODE/ETH",
"ANT/USD",
"ANT/BTC",
"ANT/ETH",
"DTH/USD",
"DTH/BTC",
"DTH/ETH",
"MIT/USD",
"MIT/BTC",
"MIT/ETH",
"STJ/USD",
"STJ/BTC",
"STJ/ETH",
"XLM/USD",
"XLM/EUR",
"XLM/JPY",
"XLM/GBP",
"XLM/BTC",
"XLM/ETH",
"XVG/USD",
"XVG/EUR",
"XVG/JPY",
"XVG/GBP",
"XVG/BTC",
"XVG/ETH",
"BCI/USD",
"BCI/BTC",
"MKR/USD",
"MKR/BTC",
"MKR/ETH",
"KNC/USD",
"KNC/BTC",
"KNC/ETH",
"POA/USD",
"POA/BTC",
"POA/ETH",
"LYM/USD",
"LYM/BTC",
"LYM/ETH",
"UTK/USD",
"UTK/BTC",
"UTK/ETH",
"VEE/USD",
"VEE/BTC",
"VEE/ETH",
"DAD/USD",
"DAD/BTC",
"DAD/ETH",
"ORS/USD",
"ORS/BTC",
"ORS/ETH",
"AUC/USD",
"AUC/BTC",
"AUC/ETH",
"POY/USD",
"POY/BTC",
"POY/ETH",
"FSN/USD",
"FSN/BTC",
"FSN/ETH",
"CBT/USD",
"CBT/BTC",
"CBT/ETH",
"ZCN/USD",
"ZCN/BTC",
"ZCN/ETH",
"SEN/USD",
"SEN/BTC",
"SEN/ETH",
"NCA/USD",
"NCA/BTC",
"NCA/ETH",
"CND/USD",
"CND/BTC",
"CND/ETH",
"CTX/USD",
"CTX/BTC",
"CTX/ETH",
"PAI/USD",
"PAI/BTC",
"SEE/USD",
"SEE/BTC",
"SEE/ETH",
"ESS/USD",
"ESS/BTC",
"ESS/ETH",
"ATM/USD",
"ATM/BTC",
"ATM/ETH",
"HOT/USD",
"HOT/BTC",
"HOT/ETH",
"DTA/USD",
"DTA/BTC",
"DTA/ETH",
"IQX/USD",
"IQX/BTC",
"IQX/EOS",
"WPR/USD",
"WPR/BTC",
"WPR/ETH",
"ZIL/USD",
"ZIL/BTC",
"ZIL/ETH",
"BNT/USD",
"BNT/BTC",
"BNT/ETH",
"ABS/USD",
"ABS/ETH",
"XRA/USD",
"XRA/ETH",
"MAN/USD",
"MAN/ETH",
"BBN/USD",
"BBN/ETH",
"NIO/USD",
"NIO/ETH",
"DGX/USD",
"DGX/ETH",
"VET/USD",
"VET/BTC",
"VET/ETH",
"UTN/USD",
"UTN/ETH",
"TKN/USD",
"TKN/ETH",
"GOT/USD",
"GOT/EUR",
"GOT/ETH",
"XTZ/USD",
"XTZ/BTC",
"CNN/USD",
"CNN/ETH",
"BOX/USD",
"BOX/ETH",
"MGO/USD",
"MGO/ETH",
"RTE/USD",
"RTE/ETH",
"YGG/USD",
"YGG/ETH",
"MLN/USD",
"MLN/ETH",
"WTC/USD",
"WTC/ETH",
"CSX/USD",
"CSX/ETH",
"OMN/USD",
"OMN/BTC",
"INT/USD",
"INT/ETH",
"DRN/USD",
"DRN/ETH",
"PNK/USD",
"PNK/ETH",
"DGB/USD",
"DGB/BTC",
"BSV/USD",
"BSV/BTC",
"BAB/USD",
"BAB/BTC",
"WLO/USD",
"WLO/XLM",
"VLD/USD",
"VLD/ETH",
"ENJ/USD",
"ENJ/ETH",
"ONL/USD",
"ONL/ETH",
"RBT/USD",
"RBT/BTC",
"UST/USD",
"EUT/EUR",
"EUT/USD",
"GSD/USD",
"UDC/USD",
"TSD/USD",
"PAX/USD",
"RIF/USD",
"RIF/BTC",
"PAS/USD",
"PAS/ETH",
"VSY/USD",
"VSY/BTC"]
		   
ask = np.zeros((len(symbols), len(clients)))
bid = np.zeros((len(symbols), len(clients)))


for row, symbol in enumerate(symbols):
    for col, client in enumerate(clients):
        
        try:
            book = client.fetch_order_book(symbol)
            ask[row, col] = book['asks'][0][0]
            bid[row, col] = book['bids'][0][0]
        except:
            pass
			
fee = 0.25
opportunities = []
 
for i, symbol in enumerate(symbols):
    for j1, exchange1 in enumerate(exchanges):
        for j2, exchange2 in enumerate(exchanges):
            
            roi = 0
            if j1 != j2 and ask[i, j1]>0:
                roi = ((bid[i, j2]*(1-fee/100)) / (ask[i, j1]*(1+fee/100)) - 1) * 100
                
                if roi>0:
                    opportunities.append([symbol, exchange1, ask[i, j1], exchange2, bid[i, j2], round(roi,2)])
                
print("Number of profitable opportunities:", len(opportunities))

opportunities = sorted(opportunities, reverse=True, key=lambda x: x[5])
print(opportunities[:10])
#print(opportunities[:3])